version: 2

sources:
  - name: bronze
    database: WALMART_DB
    schema: BRONZE
    tables:
      - name: STORE_SOURCE
      - name: DEPARTMENT_SOURCE
      - name: FACT_SOURCE
  - name: silver
    database: WALMART_DB
    schema: SILVER
    tables:
      - name: STORE
      - name: DEPARTMENT
      - name: FACT
      - name: DATE