version: 2


models:
  - name: test
    description: "DBT Model for employee table"
    columns:
      - name: test_id
        tests:
          - unique
          - not_null
          - accepted_values:
              values: ['1','2','3','4','5','6']
              config:
                severity: warn
      - name: status
        tests:
          - not_null
   
sources:
  - name: test
    database: GLUE_DB
    schema: PUBLIC
    tables:
      - name: TEST_RAW