version: 2


models:
  - name: country
    description: "DBT Model for country table"
    columns:
      - name: country_id
        tests:
          - unique
          - not_null
          - accepted_values:
              values: ['1','2','3','4','5','6']
              config:
                severity: warn
      - name: common_name
        tests:
          - not_null
   
sources:
  - name: country
    database: GLUEDB
    schema: PUBLIC
    tables:
      - name: COUNTRY_JSON