version: 2


models:
  - name: employee
    description: "DBT Model for employee table"
    columns:
      - name: emp_id
        tests:
          - unique
          - not_null
          - accepted_values:
              values: ['1','2','3','4','5','6']
              config:
                severity: warn
      - name: emp_salary
        tests:
          - salary_check
  - name: customer
    description: "DBT Model for the customer table"
  - name: customer_vw
    description: "DBT model for the customer view"
  - name: sales
    description: "DBT Model for the sales table"
  - name: product
    description: "DBT Model for the product table"
  - name: purchase
    description: "DBT Model for the purchase table"
  - name: clean_orders
    description: "DBT Model for the clean Orders"
  - name: final_order
    description: "DBT Model for the final orders"
  - name: concat_address
    description: "DBT Model for concat address"
  - name: concat_name
    description: "DBT Model for concat name"
   
sources:
  - name: employee
    database: DBT_DB
    schema: PUBLIC
    tables:
      - name: EMPLOYEE_RAW
  - name: customer
    database: DBT_DB
    schema: PUBLIC
    tables:
      - name: CUSTOMER_SRC
  - name: sales
    database: DBT_DB
    schema: PUBLIC
    tables:
      - name: SALES_SRC
  - name: product
    database: DBT_DB
    schema: PUBLIC
    tables:
      - name: PRODUCT_SRC
  - name: purchase
    database: DBT_DB
    schema: PUBLIC
    tables:
      - name: PURCHASE_SRC
  - name: orders
    database: DBT_DB
    schema: PUBLIC
    tables:
      - name: BASE_ORDERS
  - name: patient
    database: DBT_DB
    schema: PUBLIC
    tables:
      - name: PATIENT_SRC
  - name: country
    database: DBT_DB
    schema: PUBLIC
    tables:
      - name: SESSION_SRC