version: 2


models:
  - name: country
    description: "DBT Model for country table"
    columns:
      - name: country_id
        tests:
          - not_null
      - name: common_name
        tests:
          - not_null
   
sources:
  - name: country
    database: GLUEDB
    schema: PUBLIC
    tables:
      - name: COUNTRY_JSON